name: studyo_tech_interview
description: "Studyo Tech Interview"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  build_runner: ^2.4.11
  cupertino_icons: ^1.0.6
  cloud_firestore: ^5.1.0
  flutter_gen: ^5.6.0
  flutter_svg: ^2.0.10+1
  firebase_core: ^3.2.0
  fpdart: ^1.1.0
  get: ^4.6.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_gen_runner: ^5.6.0
  flutter_lints: ^3.0.0

flutter_gen:
  output: lib/core/gen/
  line_length: 80

  integrations:
    flutter_svg: true
    lottie: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700